# Site Settings
title: Sergio Costa
#url: 'https://sergiosrgtc.github.io/'
baseurl: '' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar
future: True

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Sergio Costa
tagline: Software Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I have over 10 years of experience working with Information Technology. Started as a helpdesk/infrastructure intern in my first month at university then went to work as a Java developer for few years before joining Siemens Industry Software where I worked as the coordinator of the support and maintenance team, and current work as a Software Consultant and Developer. I see myself as a pragmatic, problem solver, challenge-oriented professional, well-versed at all aspects of software development life cycle.'

#sidebar links
email: sergiosrgtc@gmail.com
phone: +5511959034538
website: https://sergiosrgtc.github.io/ #do not add http://
linkedin: sergio-costa-54310630
#github: sharu725
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
